### ISSUE TITLE
Specify the cutlass codegen for TVM

### ISSUE THREAD

**Issue by YukeWang96** [masahi/tvm-cutlass-eval#1]
How does this part of code specify the `cutlasscodegen` for code generation?

https://github.com/masahi/tvm-cutlass-eval/blob/668442303f04428104c432fc00a4065bb87b8e40/resnet50/run.py#L30-L39

**Comment by masahi** [comment]
It is done by `partition_for_cutlass`.
https://github.com/apache/tvm/blob/e7f36487dfdb6c4b7b544be155d3869002d7281b/python/tvm/relay/op/contrib/cutlass.py#L175

Each pattern is prefixed with `cutlass.` and `transform.AnnotateTarget(["cutlass"])` tells the graph partitioner what ops to partition.

**Comment by YukeWang96** [comment]
Thanks for your quick reply, I encounter another problem, after using `annotateTarget` on the defined `mod`
```
AssertionError: annotation.compiler_begin doesn't have an FTVMStrategy registered. You can register one in python with `tvm.relay.op.register_strategy`.
```
is this because of a missing strategy for the operator?

**Comment by masahi** [comment]
I don't think so. `annotation.compiler_begin` is not a real op, so there is no strategy for it. This op is supposed to disappear after you run `PartitionGraph`, have you run it?

**Comment by YukeWang96** [comment]
May I know which line or code snippet eliminates this `annotation.compiler_begin`. 
Does this line make difference?
https://github.com/apache/tvm/blob/e7f36487dfdb6c4b7b544be155d3869002d7281b/python/tvm/relay/op/contrib/cutlass.py#L256

**Comment by masahi** [comment]
As I said above, it's `PartitionGraph`'s job https://github.com/apache/tvm/blob/e7f36487dfdb6c4b7b544be155d3869002d7281b/python/tvm/relay/op/contrib/cutlass.py#L258

**Comment by YukeWang96** [comment]
It works, thanks a lot!
