### ISSUE TITLE
Check the generated CUTLASS code

### ISSUE THREAD

**Issue by YukeWang96** [masahi/tvm-cutlass-eval#2]
Is there any way to check/print the generated CUTLASS code?

**Comment by masahi** [comment]
If you run `test_cutlass.py`, you will see generated cutlass code under the `tmp` directory (check `lib0.cu` file)

**Comment by YukeWang96** [comment]
It works in `test_cutlass.py`. 
However, when I want to figure out which statement that generate the `*.cu`, I use the following code
```
lib = relay.build(mod, target, params=params)
lib = build_cutlass_kernels(lib, sm=75,  tmp_dir="./tmp", lib_path="compile.so")
```
It will only keep the `*.o` files while no `*.cu` under the `tmp/` , am I missing something?

**Comment by masahi** [comment]
I think this should be `export_library()` call at

https://github.com/apache/tvm/blob/6d35f0bbdf656d393b0722cb93cd213217781c9d/python/tvm/contrib/cutlass/build.py#L353

This is where we dump the .cu file and invoke nvcc.

**Comment by YukeWang96** [comment]
I also found that when I comment out `tune_cutlass_kernels` such as https://github.com/apache/tvm/blob/4babd36481b7108bf50df5c3b256c95c0d9c3291/tests/python/contrib/test_cutlass.py#L181-L183 there will be no `.cu` file generated.

**Comment by YukeWang96** [comment]
Finally, I figure out the reason: The annotated needs to identify the operators that will be lowering to CUTLASS backend.
Thanks!

**Comment by masahi** [comment]
You are welcome to join `tlcpack` slack (aka TVM slack) if you want more high-bandwidth communication with me or others. The invitation link is below.

https://join.slack.com/t/tvmai/shared_invite/zt-foemgff5-9pC0jateEAdpoZImfxxMew

**Comment by YukeWang96** [comment]
Sure, will do. Thanks for your nice suggestion!
