### ISSUE TITLE
What is the precise meaning of cuDNN and TensorRT in the result table?

### ISSUE THREAD

**Issue by umiswing** [masahi/tvm-cutlass-eval#4]
Hello! I am interested in TVM's work on cutlass. I am a bit confused about the results table. Does the inclusion of cuDNN and TensorRT in the table mean that TVM is running models using the kernels/sub-graphs provided by cuDNN and TensorRT? If that is the case, why did TVM add support for cutlass when TensorRT is faster?

**Comment by masahi** [comment]
> Does the inclusion of cuDNN and TensorRT in the table mean that TVM is running models using the kernels/sub-graphs provided by cuDNN and TensorRT

Yes for cuDNN but no for TRT. The TRT result is for reference only, the results were obtained by running TRTorch on resnet or running the BERT demo in the TensorRT repo. And CUTLASS is generally faster than cuDNN.
